### ISSUE TITLE
KAPT error when trying to launch the App

### ISSUE THREAD

**Issue by Martinocom** [natario1/Firestore#4]
Hello!
After adding your library on my project, it wouldn't start. The only thing changed during development of this project was the adding of maven repo, addig your library and another one for "wizard-like" screen.

I provided to remove the library and the maven repo, but the project is not compiling. The problem is very generic: 
`e: [kapt] An exception occurred: java.lang.NoClassDefFoundError: com/squareup/kotlinpoet/TypeName`.

I can provide also a screenshot of what happening when I'm trying to build.
![screeen](https://user-images.githubusercontent.com/17514549/72666327-513c9000-3a11-11ea-9327-ef757bbc171a.png)

Cleaning, reopening, rebuilding, restarting PC doesn't work.

Tired of everything and before opening this issue, I tried to apply manually plugins that is showing me as "missing". I added
```
    implementation 'org.jetbrains.kotlinx:kotlinx-metadata-jvm:0.1.0'
    implementation 'com.squareup:kotlinpoet:1.5.0'
```
Then, to resolve next issue, I went back in the `1.3.41` version of Kotlin (from the `1.3.61`) and it _would_ compile, **but** generates another problem that I'm unable to solve:

`More than one file was found with OS independent path 'META-INF/metadata.kotlin_module'`

I really don't know what I messed up. If I remove the `katp` part everything works, but, obviously, when I'm going to use your FireStore classes it throws me exceptions.

So... Any help would be appreciated.
Thanks.

**Comment by natario1** [comment]
We now have a demo app that you can use as a sample.

**Comment by Martinocom** [comment]
I tried to add missing dependencies I could found on your build.gradle
```
        classpath 'com.github.dcendents:android-maven-gradle-plugin:2.1'
        classpath 'com.jfrog.bintray.gradle:gradle-bintray-plugin:1.8.4'
        classpath "org.jetbrains.dokka:dokka-android-gradle-plugin:$dokkaVersion"
```
but still nothing. I added also missing repos:
```
        mavenCentral()
        maven { url "https://kotlin.bintray.com/kotlinx/" }
```
but still nothing.

I really don't know how I messed up the things (it worked for some time), but I just remove the plugin and will do without it :(

**Comment by worker4food** [comment]
A patch for reproducing this error in a demo app (from worker4food/firestore@fc37fe0):

```diff
diff --git a/demo/build.gradle.kts b/demo/build.gradle.kts
index f46a04f..bd6bce5 100644
--- a/demo/build.gradle.kts
+++ b/demo/build.gradle.kts
@@ -32,8 +32,8 @@ android {

 dependencies {

-    implementation(project(":firestore"))
-    kapt(project(":compiler"))
+    implementation("com.otaliastudios:firestore:0.5.1")
+    kapt("com.otaliastudios:firestore-compiler:0.5.1")

     val kotlin = rootProject.extra["kotlinVersion"]
     implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin")
```

[Build log](https://github.com/worker4food/Firestore/runs/422639940?check_suite_focus=true#step:4:42)

**Comment by natario1** [comment]
Thanks @worker4food I will take a look! To workaround you should be able to compile by declaring firestore-compiler dependencies in your own project.

**Comment by JobGetabu** [comment]
**This is the stacktrace**

```
Caused by: com.sun.tools.javac.processing.AnnotationProcessingError: java.lang.NoClassDefFoundError: com/squareup/kotlinpoet/TypeName
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$ProcessorState.<init>(JavacProcessingEnvironment.java:749)
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors$ProcessorStateIterator.next(JavacProcessingEnvironment.java:828)
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:924)
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1267)
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1381)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1263)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1162)
        ... 35 more
Caused by: java.lang.NoClassDefFoundError: com/squareup/kotlinpoet/TypeName
        at com.otaliastudios.firestore.compiler.Processor.init(Processor.kt:38)
        at org.jetbrains.kotlin.kapt3.base.incremental.IncrementalProcessor.init(incrementalProcessors.kt:33)
        at org.jetbrains.kotlin.kapt3.base.ProcessorWrapper.init(annotationProcessing.kt:156)
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$ProcessorState.<init>(JavacProcessingEnvironment.java:700)
        ... 41 more
Caused by: java.lang.ClassNotFoundException: com.squareup.kotlinpoet.TypeName
        ... 45 more

```
